### ISSUE TITLE
webapp not work in Safari

### ISSUE THREAD

**Issue by young310** [tinode/webapp#80] opened 2021-07-17 17:16 UTC
**Describe the bug**
Login view does not show properly/normaly

**To Reproduce**
1. Go to https://sandbox.tinode.co/

**Expected behavior**
normal login web page

**Screenshots**
<img width="1440" alt="Screen Shot 2021-07-18 at 01 14 40" src="https://user-images.githubusercontent.com/8056293/126044744-e1050e43-a692-4795-aa82-a2ba24a46b7f.png">

**Environment (please complete the following information):**
https://sandbox.tinode.co

**Console log**
N/A

**Additional context**
you can see the following error log from safari console
ReferenceError: Can't find variable: BroadcastChannel
Failed to load resource: the server responded with a status of 404 ()

**Comment by or-else** [comment] 2021-07-17 17:20
Safari is broken by design:
https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel

**Comment by young310** [comment] 2021-07-17 17:23
Maybe a little try{}catch{} can prevent from the entire website crash?

**Comment by or-else** [comment] 2021-07-17 17:29
I added a check: https://github.com/tinode/webapp/commit/a24ee01b37df6151cc6623e6224f9bd70e5849f6

**Comment by young310** [comment] 2021-07-30 05:27
> I added a check: [a24ee01](https://github.com/tinode/webapp/commit/a24ee01b37df6151cc6623e6224f9bd70e5849f6)

Hi or-else
the service worker has the similar issue.

**Comment by or-else** [comment] 2021-07-30 16:40
Thanks! Fixed: https://github.com/tinode/webapp/commit/122fd018d0221626bca7889e23da54d5a414e3ba

**Comment by or-else** [comment] 2021-08-03 20:22
Released in 0.17.7

**Closed by or-else** 2021-08-03 20:22 UTC
Labels: bug
