### ISSUE TITLE
Previews of new messages in the contacts list and new message badges disappear after page reload.

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#73] opened 2021-05-19 09:24 UTC
Client: TinodeWeb/0.17.0
Browser: Chrome

This problem already has been described [here](https://github.com/tinode/webapp/issues/70) but after fixing it it still exists, and now looks that there are even more problems as before fixing it.

After page reload in the webapp disappear not only previews of messages but also badges that show numbers of new messages.

**To reproduce**

In Alice´s contact list Bob´s contact should not be selected. Otherwise you will not be able to see the problem.

Bob sends message to Alice. In Alice´s contact list Bob jumps to the top of the contacts and appears badge indicating that there is a new message from Bob as it should be:

![app20](https://user-images.githubusercontent.com/54183931/118778171-bb717900-b881-11eb-8de9-8c6e36f33c12.png)

but message preview does not update. It shows previous message, not recently received.

Now Alice reloads the page without reading messages from Bob.

After reloading the page there are no message preview at all and badge with number of new messages disappears.

![app22](https://user-images.githubusercontent.com/54183931/118780125-a4338b00-b883-11eb-9ec2-5439a84b5dec.png)

If after receiving a new message Bob in Alice's contact list was not at the top, after page reload Bob's contact will return back to the same place where it was after receiving a new message.

I even can not understand the pattern of some things. Sometimes if there are more than 1 new message, after page reload appears badge but indicates that there is only 1 new message. Sometimes if there are new messages in more than 1 topic, appears badge with new messages number only in 1 topic.

If there are message previews implemented, previews should appear not only for selected contact but for all contacts who send new messages.

As I understand the webapp does not fix the number of new messages for each topic in the IndexedDB but on page reload loads all topics from the server, calculates the number of new messages and then only updates this number or hides the badge with number of new messages. If it's so, I can not understand why badges with numbers of new messages don't appear after page reload if `readId` and `sedId` are different on the server.

**Possible solutions**

I don't know solution for badges with the number of new messages. It was working correctly before introducing previews of the messages.

Message previews. This would not only fix the problem with previews of the messages but also increase the accuracy of Tinode (message received/not received).
If webapp is connected to the server and new message is coming, Webapp should receive not only `pres ` but also the new message (without a need to select the contact to receive it) and should update message preview in the contacts list.

**Comment by or-else** [comment] 2021-05-19 20:45
> After page reload in the webapp disappear ... also badges that show numbers of new messages

Fixed in https://github.com/tinode/tinode-js/commit/4eadac9bcc06ffb3e3975e57421709fdb164c8ad

**Comment by or-else** [comment] 2021-05-19 21:56
> After page reload in the webapp disappear not only previews of messages

Fixed in
https://github.com/tinode/tinode-js/commit/f55d5cd4a3a321cb1f79e3e1fccd160695ac50ee

**Comment by sanmiguel2019** [comment] 2021-05-20 15:38
Unread count does not disappear anymore but previews still disappear. I don't understand if it has been fixed or can not be fixed.

**Comment by or-else** [comment] 2021-05-20 18:35
If after clearing cache and applying tinode/tinode-js@f55d5cd you still see previews disappearing, please list steps to reproduce.

**Comment by sanmiguel2019** [comment] 2021-05-21 17:34
Yes, I cleared cache and  applied changes tinode/tinode-js@f55d5cd

Previews are not appearing and are disappearing if a topic is not selected.

1. Bob is going to send a message to Alice. Bob's contact in Alice's contact list is not selected and looks like this:

![app20a](https://user-images.githubusercontent.com/54183931/119175442-be2ac480-ba61-11eb-98db-46edb0681ba9.png)

As you can see, the message preview is "test test test test"

2. Bob sends a new message to Alice with text "Hi Alice".

Appears a badge in Alice's contacts list showing that there is 1 new message from Bob:

![app20](https://user-images.githubusercontent.com/54183931/119175790-2f6a7780-ba62-11eb-8a0d-add8e8fd97d8.png)

but message preview does not change from "test test test" to "Hi Alice"

4. Alice reloads the page without reading message from Bob. Now there is still a badge showing 1 message from Bob but no message preview at all:

![app20c](https://user-images.githubusercontent.com/54183931/119176081-8f611e00-ba62-11eb-9c90-fe7c29895559.png)

For sender everything is OK. Problem is in the recipients contact list if a contact where message comes from is not selected.

**Comment by or-else** [comment] 2021-05-21 17:42
> 2. ... but message preview does not change from "test test test" to "Hi Alice" 

This is expected, see my comment here: https://github.com/tinode/webapp/issues/74

> 4. ... but no message preview at all

I cannot reproduce. I suspect you have not applied https://github.com/tinode/tinode-js/commit/f55d5cd

**Comment by pwFoo** [comment] 2021-05-29 11:40
Sounds similar to my problem here #72 

Push works fine, sometimes message preview is shown in contact list, but message isn't shown in topic. Sometimes shown as "deleted message" if I answer before the missing message is loaded...

So I need to open / close webapp / topic many times over some minutes until the message appears. With that problem my tinode isn't usable anymore.

**Comment by or-else** [comment] 2021-05-29 15:41
List steps to reproduce.

> With that problem my tinode isn't usable anymore.

Then don't use it.

**Comment by pwFoo** [comment] 2021-05-29 18:40
We hope it will fixed with one of the next releases... 
Most users switched to other messengers because of that problem. 

Only two users still try to test and reproduce that bug.
But is reliable each time I get a new message without active in the topic...

**Comment by or-else** [comment] 2021-05-29 19:26
Do you understand that the https://github.com/tinode/tinode-js/commit/f55d5cd needs to be applied? Or wait for the next release.

**Comment by pwFoo** [comment] 2021-05-30 07:42
Looks like I need to wait for the next release. I patched my installation and it stopped working.
```
Uncaught SyntaxError: Invalid or unexpected token
index.prod.js:1 Uncaught ReferenceError: Tinode is not defined
    at e (index.prod.js:1)
    at index.prod.js:1
    at index.prod.js:1
```

**Closed** 2021-06-02 04:17 UTC
Labels: bug
