### ISSUE TITLE
Inline images problem in devel version

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#68] opened 2021-04-28 10:07 UTC
Broeser: Chrome

Yesterday I downloaded the devel version and there are some problem with dimensions of online images.
Firstly, I was thinking that I have this problem because I have modified the css file - colors etc, but then I rebuilded the app with original css file and problem still exists.

**Original css file**

1. Each image has different dimensions. I don't know, probably it's by design, but it creates a sense of chaos. If it's by design, I suggest to display all the images in the conversation of the same size, regardless of the original size. It will make the conversation visually clean.
2. Right bubble. The right margin is bigger then the left.

![app1](https://user-images.githubusercontent.com/54183931/116383346-a8353580-a80e-11eb-9702-8c4dff7e40da.png)

3. Horizontal images look huge but vertical images small.
4. In case of vertical images or small horizontal images, if message does not contain any text but only image, the date appears not below of the image but in the same line.

![app2](https://user-images.githubusercontent.com/54183931/116384212-8be5c880-a80f-11eb-9415-0e564162ab93.png)

**Modified css file**

Dimensions of inline images in `rem` make images very huge. Probably it's ok in the mobile phones but in computer 1 image can occupy almost 50% of the conversation window. In modified css file and I had online-image dimensions set in px to have more control of dimensions (the same with and the same size). Now it does not work. Values in px are being ignored and image appears even bigger than the bubble, and horizontal scrollbar appears

![app3](https://user-images.githubusercontent.com/54183931/116386984-3b239f00-a812-11eb-80c9-e68acdedc30c.png)

I saw problems with online images in some previous version but then everything looked ok. Now there is a problem again.

**Comment by or-else** [comment] 2021-04-28 23:36
Case 1: Images are displayed at the original aspect ratio. The only way to make them appear the same is to crop them to a different ratio. I suppose it's a matter of taste. I'm not going to do it for this release, but I'll see what others are doing and make add this feature in the next release. 
Case 2: Can you fix it?
Case 3: The scale is calculated dynamically from the viewport size. If your viewport is landscape while the image is portrait then the image is made particularly narrow. I don't see how to fix it except by cropping the image (case 1).
Case 4: I made some tweaks to push it to the bottom-right: 271fbc4. Unfortunately it results in some unnecessary vertical spacing in some cases. It can be fixed if images are cropped to be of certain size (case 1). You are also welcome to take a shot at it.

> Modified css file

I added `min-width` and `min-height` to images and that probably affected your code. The `min-width` and `min-height` are needed for proper display of broken images.

**Comment by sanmiguel2019** [comment] 2021-04-29 08:24
> Case 2: Can you fix it?
> Case 4: I made some tweaks to push it to the bottom-right: 271fbc4. Unfortunately it results in some unnecessary vertical spacing in some cases. It can be fixed if images are cropped to be of certain size (case 1). You are also welcome to take a shot at it.

Adding
`display:block;`
to
`.inline-image`
for me fixed the problem. Now timestamp is below of the image even if image is small, and left and right margin are of the same width.

**Comment by or-else** [comment] 2021-04-29 16:59
> Adding
> display:block;
> to
> .inline-image

Unfortunately it's not that simple. It's going to produce wrong layouts too.

**Comment by sanmiguel2019** [comment] 2021-04-29 17:26
Then I don´t know. I was trying to set up online images of the same size but probably its not so simple either.

> Case 1: Images are displayed at the original aspect ratio. The only way to make them appear the same is to crop them to a different ratio. I suppose it's a matter of taste. I'm not going to do it for this release, but I'll see what others are doing and make add this feature in the next release.

It´s a matter of taste but as I have seen, many users are doing increible things with their photos, for example by cropping an image so that the witdh is of some 100 px and height of some 400px. Dynamic calculation of such an image will produce a tiny resized image.

That´s why I preffer to have all the images in chat messages of the same size even if some parts are hidden. Users can click on the image to see it in full size/dimensions. I guess it can be done without cropping, with css, by using image as a background.

I was playing with it works. I use image as a background and a transparent gif as image. The only problem is that when I click on image to see it in full size, appears not the image but transparent gif.

It´s one of the versions of my experiments. I tried it in different ways but always the same problem to show the large image

```
case 'IM':
        // Additional processing for images
        if (data) {
          attr.className = 'inline-image';
          //const dim = fitImageSize(data.width, data.height,
            //Math.min(this.props.viewportWidth - REM_SIZE * 4, REM_SIZE * 36), REM_SIZE * 24, false) ||
            //{dstWidth: BROKEN_IMAGE_SIZE, dstHeight: BROKEN_IMAGE_SIZE};
            
          attr.href = this.props.tinode.authorizeURL(sanitizeImageUrl(attr.src));
          attr.src = 'img/transparent.gif';
          attr.style = {
           width:'200px',
           height:'160px',
           backgroundPosition:'center',
           backgroundRepeat:'no-repeat',
           backgroundSize:'cover',
           backgroundImage:'url(' + attr.href + ')'
          //width: dim.dstWidth + 'px', 
          //height: dim.dstHeight + 'px' 
          };
       
          if (!Drafty.isProcessing(data)) {
            //attr.src = this.props.tinode.authorizeURL(sanitizeImageUrl(attr.src));
            attr.alt = data.name;
            //if (attr.src) {
            if (attr.href) {
              attr.onClick = this.handleImagePreview;
              attr.className += ' image-clickable';
            } else {
              attr.src = 'img/broken_image.png';
            }
          } else {
            // Use custom element instead of <img>.
            el = UploadingImage;
          }
        }
        break;

  handleImagePreview(e) {
    e.preventDefault();
    this.props.onImagePreview({
      url: e.target.href,
...



```

**Comment by or-else** [comment] 2021-04-29 17:41
I made a few more tweaks: 0add66f
It looks OK now without breaking the Drafty concept.

**Comment by or-else** [comment] 2021-04-29 17:42
> 100 px and height of some 400px. Dynamic calculation of such an image will produce a tiny resized image.

Yes, but it's their decision, is it not?

**Comment by or-else** [comment] 2021-04-29 17:44
>  I use image as a background and a transparent gif as image.

It's not too difficult to force a certain aspect ratio. For me it's a matter of deciding to do it rather than implementation.

**Comment by sanmiguel2019** [comment] 2021-04-30 17:53
> Yes, but it's their decision, is it not?

Yes, it´s their decision but users send images to someone and I am not sure that all recipients will be happy to see the chat window like this.

![tin3](https://user-images.githubusercontent.com/54183931/116732972-65788680-a9e3-11eb-87c4-8350d552e6ba.jpg)

I mentioned disproportionate images because some years ago I saw a situation where it was done regularry as a form trolling. I think that all the clients must have a minimum height/weight of uploading images. If not, it's possible to upload even 1px X 5000px image. And you can see in the screenshot, how it looks if the image is narrower than the bubble's min width. All social networks, whatsapp have fixed width/height thumbnails. I think the same should be done in Tinode to make it look m professional.

> I made a few more tweaks: 0add66f
> It looks OK now without breaking the Drafty concept.

I applied the changes. Now it looks like this:

![tin5](https://user-images.githubusercontent.com/54183931/116734451-2ba87f80-a9e5-11eb-8c65-ddc1951e939c.jpg)


I am not sure but I guess before I had all margins of the same size but now the top margin looks wider.

It's not an urgent issue but problems with images still exist.

**Comment by or-else** [comment] 2021-04-30 18:08
>  it was done regularry as a form trolling

This is not a forum: it's either a chat if a relatively small number of users, or a channel with just one publisher.
I'm not opposed in general. I do see your point. I'm just not sure it's the best experience. Or it needs to be very carefully applied. It's not clear when to crop the image and when to leave the original aspect ratio. 

> but now the top margin looks wider

It's something on your end. I see the opposite:

<img width="605" alt="Screenshot 2021-04-30 at 11 05 55" src="https://user-images.githubusercontent.com/5938143/116735933-e3468d00-a9f7-11eb-882c-75ea35d2ca0a.png">

**Comment by or-else** [comment] 2021-04-30 18:19
I just checked. WhatsApp crops both horizontally and vertically on web and android, Telegram crops only horizontally and only on android.

**Comment by sanmiguel2019** [comment] 2021-04-30 18:36
And one more thing related to this issue. If Tinode in the future is going to support multiple images in the same message, this problem will appear again. To neatly combine images they mush have at least the same height. For example, Whatsapp combines images in this way:

![tin7](https://user-images.githubusercontent.com/54183931/116738679-ad4edc00-a9ea-11eb-896a-a3b44b9e4c78.jpg)

If Images are displayed separately, it occupies a lot of space. If there is a need to find some message, scrolling trough large images could be annoying.

I mention Whatsapp like example because I like the way how they do it. Even if I send a message with 3 images (without any text) and later send one more message with images and without text, the last message will not appear as a separate message. Images are added to the first message.

Iy´s just my opinion to make Tinode better.

**Comment by or-else** [comment] 2021-04-30 18:38
It's just work. These things take time and effort.

**Comment by sanmiguel2019** [comment] 2021-05-01 17:33
I'm desperate. Spent several hours trying to resolve this issue but without any success.
Rebuilded the app with the original css file. Yes, It gives the result as you posted:

> It's something on your end. I see the opposite:
> 
> <img alt="Screenshot 2021-04-30 at 11 05 55" width="605" src="https://user-images.githubusercontent.com/5938143/116735933-e3468d00-a9f7-11eb-882c-75ea35d2ca0a.png">

but only on the right side and not all the images. 

Right side: some images have equal left/tight margins, some not.



Left side: if image does not contain any text, it has a huge right margin:






On the left side images looks ok only if they contain text. Images without text look like this:


I added again

display:block;
to
.inline-image

**Comment by or-else** [comment] 2021-05-02 01:45
This

<img width="224" alt="Screenshot 2021-05-01 at 18 43 57" src="https://user-images.githubusercontent.com/5938143/116799329-1d4f8600-ab01-11eb-9c52-903db08a2a91.png">

is fixed in https://github.com/tinode/webapp/commit/1023e80fa6f82cef983ef8fc7d0fb3988036a348

**Comment by or-else** [comment] 2021-05-02 02:18
Regarding wrong margins on the left side, I don't see it:

<img width="593" alt="Screenshot 2021-05-01 at 19 17 35" src="https://user-images.githubusercontent.com/5938143/116800002-d021e300-ab05-11eb-8841-39ba47db2461.png">

**Comment by or-else** [comment] 2021-05-02 03:02
Make sure you are using the latest devel.

**Comment by sanmiguel2019** [comment] 2021-05-02 13:09
I forgot to apply the latest changes. Now everything looks OK. Thank you.

**Comment by sanmiguel2019** [comment] 2021-05-02 14:19
Well, looks OK only in computer. In my mobile phone I see a horizontal scrollbar because the bubble is wider than the screen. When I turn my phone horizontally (and contact list appears), the horizontal scrollbar disappears.

![app8](https://user-images.githubusercontent.com/54183931/116816389-9c70a880-ab59-11eb-91fb-198b236acea9.png)

**Comment by or-else** [comment] 2021-05-02 16:49
I made a fix which reduces the maximum width of the bubbles on mobile: 430b2db
See if it helps.

**Comment by sanmiguel2019** [comment] 2021-05-02 18:47
Unfortunately, not
![app18](https://user-images.githubusercontent.com/54183931/116823920-35fe8100-ab7f-11eb-870a-cb8f11988cdc.png)

**Comment by or-else** [comment] 2021-05-02 18:57
What is the width of the screen in your phone (in pixels)?

**Comment by sanmiguel2019** [comment] 2021-05-02 19:21
Can not find it in the phone settings. It´s Galaxy A51. All online tools report: 412x915 px.

**Comment by or-else** [comment] 2021-05-02 23:54
I cannot reproduce:

<img width="383" alt="Screenshot 2021-05-02 at 16 52 29" src="https://user-images.githubusercontent.com/5938143/116831871-ab3b7780-abba-11eb-8597-03c9a49b97fb.png">

<img width="348" alt="Screenshot 2021-05-02 at 16 53 41" src="https://user-images.githubusercontent.com/5938143/116831908-d7ef8f00-abba-11eb-8d7c-387ef0ce635d.png">

**Comment by or-else** [comment] 2021-05-03 00:03
Please attach your image with the size which creates the problem. I'll try to reproduce with that image.

**Comment by sanmiguel2019** [comment] 2021-05-03 11:11
I deleted all the messages and the problem is gone. When I send new messages with images and there is no horizontal scrollbar anymore.

**Comment by or-else** [comment] 2021-05-03 14:49
All bugs are fixed. Please file new separate feature requests for image grouping and for for fixed aspect ratio of thin images. Thanks.

**Closed by or-else** 2021-05-03 14:49 UTC
Labels: feature request
