### ISSUE TITLE
contact-views will not sort right now after send message in the topic

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/webapp#37] opened 2019-09-02 03:37 UTC
when i send a message in my selected topic such as group1, the topic will not go up right now.
i then click another topic,and leave,and then sub group1, then group1 go up.

i check the sort algorithm is like:return (b.touched || 0) - (a.touched || 0),
but after send message, the "touched" not updated right now,So I modify the code like this:
in  tnMeContactUpdate(what, cont) {
  //call a new  func and send the cont.updated 
else if (what == 'read') {
      //cont:{"updated":"2019-09-02T02:01:22.566Z"
      this.resetContactListWithUpdated(cont.updated);
    }
.........
}

the new func like resetContactList:
resetContactListWithUpdated(updated){
    const newState = {
      chatList: []
    };
    if (!this.state.ready) {
      newState.ready = true;
    }
    this.tinode.getMeTopic().contacts((c) => {
      if (this.state.topicSelected == c.topic) {
        newState.topicSelectedOnline = c.online;
        newState.topicSelectedAcs = c.acs;
        //force the topic touched as updated
        c.touched=updated;
      }
      newState.chatList.push(c);
    });
    // Merge search results and chat list.
    newState.searchableContacts = TinodeWeb.prepareSearchableContacts(newState.chatList, this.state.searchResults);
    this.setState(newState);
 }

after then:
when i send a message in a topic, the topic immediately go up.
but i think this way is not the best solution, The best solution should fix the "touched"
on the server side.

**Comment by or-else** [comment] 2019-09-02 05:49
Looking into it.

**Comment by or-else** [comment] 2019-09-02 06:09
It looks like regression due to https://github.com/tinode/webapp/issues/35

Basically, this: https://github.com/tinode/webapp/commit/f1744c3f69de9579854cbfed64e706ab158dec4b#diff-d882887c8b301435fa55c15bd26a7c10R61

**Comment by pcgpcgpcg** [comment] 2019-09-02 06:21
#35 only solved the  always sort chatList when invalidate. Maybe not the solution for this issue, I will try and tell the result

**Comment by or-else** [comment] 2019-09-02 06:29
`prevProps.chatList != this.props.chatList` is `false` when `touched` changes in one of the contacts. As a result the contact list is not redrawn.

**Comment by or-else** [comment] 2019-09-02 06:29
I need to deep-compare `prevProps.chatList` and `this.props.chatList` instead of just `!=`.

**Comment by pcgpcgpcg** [comment] 2019-09-02 06:45
I think it's not the deep-compare problem,because when i send a message,server reply ctrl message with new "updated" time, but the "touch" time not updated.

**Comment by or-else** [comment] 2019-09-02 06:52
No that's not a bug. It's by design. The server does not update things which the client can update itself. Touched is updated by the client here:
https://github.com/tinode/tinode-js/blob/master/src/tinode.js#L4250

It really is due to shallow compare instead of deep compare.

**Comment by pcgpcgpcg** [comment] 2019-09-02 06:52
Another reason is the issue also exist in tindroid.
So in tindroid, we also should first leave the topic, then re enter the topic to make the "touched" updated from server.

**Comment by pcgpcgpcg** [comment] 2019-09-02 06:54
ok.Thank you! I should deep into the sdk code

**Comment by or-else** [comment] 2019-09-02 06:57
It appears that Tindroid has a different bug with the same end result:

https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/Topic.java#L800

The `touched` is just not updated on message delivery.

**Comment by pcgpcgpcg** [comment] 2019-09-02 07:01
will very appreciate for your fix

**Comment by or-else** [comment] 2019-09-02 07:50
Will do.

**Comment by pcgpcgpcg** [comment] 2019-09-02 10:51
i just fix it, deep compare is not the only problem. 
The main problem is   contacts not sync with topic. so I add these:
**in tinode-web.jsx,add a new state "latestSendTs":**
 getBlankState() {
    return {
      //just temp resolve as the deep compare for chatList
    + latestSendTs:"",
      // Chats as shown in the ContactsView
      chatList: [],  
  }
}

**change the resetcontactlist as:**
 resetContactList() {
    const newState = {
      chatList: []
    };

    if (!this.state.ready) {
      newState.ready = true;
    }

    console.log(`tinode:getMeTopic().contacts`);

    this.tinode.getMeTopic().contacts((c) => {
      
      if (this.state.topicSelected == c.topic) {
        newState.topicSelectedOnline = c.online;
        newState.topicSelectedAcs = c.acs;
        //chatList not means topicList,so sync the touched for sort
        c.touched=this.tinode.getTopic(c.topic).touched;
        //temparary for solve the deep compare problem  
        console.log("tinode:topicSelected="+this.tinode.getTopic(c.topic));    
        newState.latestSendTs=this.tinode.getTopic(c.topic).touched;
      }
      
      newState.chatList.push(c);
    });
    // Merge search results and chat list.
    newState.searchableContacts = TinodeWeb.prepareSearchableContacts(newState.chatList, this.state.searchResults);
    this.setState(newState);
  }

**in render() add:**
+ latestSendTs={this.state.latestSendTs}
    chatList={this.state.chatList}

**in sidepanel-View.jsx render() add:**
 + latestSendTs={this.props.latestSendTs}
    chatList={this.props.chatList}

**in contacts-view.jsx, change componentDidUpdate as:**
 componentDidUpdate(prevProps, prevState) {
    if (prevProps.chatList != this.props.chatList||prevProps.latestSendTs!=this.props.latestSendTs) {
      console.log(`tinode:componentDidUpdate prev=${prevProps.latestSendTs} latestSendTs=${this.props.latestSendTs}`);
      const newState = ContactsView.deriveStateFromProps(this.props);
      this.setState(newState);
      if (newState.unreadThreads != prevState.unreadThreads) {
        updateFavicon(newState.unreadThreads);
      }
    }
  }

**Comment by pcgpcgpcg** [comment] 2019-09-02 10:52
the key code is:
 c.touched=this.tinode.getTopic(c.topic).touched;

**Comment by or-else** [comment] 2019-09-02 13:35
Could you please send a pull request?

**Comment by or-else** [comment] 2019-09-02 15:34
Actually, no need to send the pull request. The https://github.com/tinode/tinode-js/commit/16511fffcd2abe92d3908dc2f48897c62c47360c fixes it. Thanks!

**Comment by pcgpcgpcg** [comment] 2019-09-03 01:12
Great fix, Thank you!

**Comment by or-else** [comment] 2019-09-03 12:39
Released in https://github.com/tinode/webapp/releases/tag/v0.16.1-rc2

**Closed by or-else** 2019-09-03 12:39 UTC
Labels: bug
