### ISSUE TITLE
Audio Files Cannot be Recorded in iOS Browser

### ISSUE THREAD

**Issue by akeybl** [tinode/webapp#121] opened 2023-04-12 18:42 UTC
STR:
1) Open Chrome on iOS and go to https://sandbox.tinode.co/
2) Login with alice/alice123
3) Click on Carol Xmas
![IMG_A1321BA6DBD7-1](https://user-images.githubusercontent.com/1084865/231554387-754b64d5-0538-4499-b259-b5266ddce1e3.jpeg)

4) Attempt to start audio recording
![IMG_6531](https://user-images.githubusercontent.com/1084865/231554418-9748fb13-08c2-49c8-a0fd-3c496e7ca2d6.PNG)

5) Try hitting send... maybe it's working?
![IMG_6532](https://user-images.githubusercontent.com/1084865/231554455-5904bb1f-4ef5-481d-ac8b-62ef2fc1aff4.PNG)

Nothing in the bottom bar is interactable at this point.

**Comment by or-else** [comment] 2023-04-14 22:20
The issue is the same as with https://github.com/tinode/webapp/issues/122: Sarafi only supports `audio/mp4`. I'll see if there is an easy fix for this. If there is no easy fix I'll just make sure it does not crash.

**Comment by or-else** [comment] 2023-04-15 00:59
Recording now works, no more crashes. Playback of audio recorded in Safari will work in Safari once https://github.com/tinode/chat/commit/dda74cddc9d4f8750b38f86e65925e74eb4a8e3e is deployed.

**Comment by or-else** [comment] 2023-04-24 21:38
No update in while. I assume all is fine, closing as fixed.

**Closed by or-else** 2023-04-24 21:38 UTC
Labels: bug

**Comment by akeybl** [comment] 2023-05-12 16:35
Apologies for the delay, confirmed working!
