### ISSUE TITLE
TypeError: this.props.onCancel is not a function. (In 'this.props.onCancel()', 'this.props.onCancel' is undefined)

### ISSUE THREAD

**Issue by young310** [tinode/webapp#89] opened 2021-11-30 08:07 UTC
If you want to ask a question, please post to https://groups.google.com/d/forum/tinode instead.
---

**Describe the bug**
When sending the reset email, the ok button on "an email has been sent to ..." is not working.

**To Reproduce**
1. Click reset password
2. Enter 'email' and submit
3. Click on ok button

**Expected behavior**

**Screenshots**

![Screen Shot 2021-11-30 at 16 06 14](https://user-images.githubusercontent.com/8056293/144009034-7da291ad-be52-433a-aa7e-98a2ec3ce41e.png)

**Environment (please complete the following information):**
 - OS: Mac OS
 - Browser:  Safari
 - TinodeWeb Version [e.g. 0.17.10]

**Console log**
[Error] TypeError: this.props.onCancel is not a function. (In 'this.props.onCancel()', 'this.props.onCancel' is undefined)
	rg (react-dom.production.min.js:56:366)
	(anonymous function) (react-dom.production.min.js:66:171)
	(anonymous function) (react-dom.production.min.js:240:294)
	ti (react-dom.production.min.js:30:409)
	hg (react-dom.production.min.js:59:151)
	be (react-dom.production.min.js:46)
	he (react-dom.production.min.js:45:113)
	he
	unstable_runWithPriority (react.production.min.js:24)
	(anonymous function) (react-dom.production.min.js:240:160)
	Ki (react-dom.production.min.js:44:408)

**Additional context**
NA

**Comment by or-else** [comment] 2021-11-30 17:29
I cannot reproduce in `devel`.

**Comment by or-else** [comment] 2021-12-21 20:53
No update in 3 weeks. Closing.

**Closed by or-else** 2021-12-21 20:53 UTC
Labels: cannot reproduce
